---
title: "NBA League Averages Visualizations"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(plotly)
library(ggplot2)
library(dplyr)
library(shiny)
library(readr)
library(magrittr)

### 身長の表記をcmにする
feet_to_meter = function(Ht = "3-1"){
  res = as.numeric(strsplit(Ht, "-")[[1]]) * c(30.48, 2.54)
  return(sum(res))
}

## 前処理を行う関数
preprocess_nba_league_avg_data = function(dat_avg){
  
  ## ちゃんとデータが取れている年度に限定する
  dat_avg %>% 
    filter(Rk >= 2) %>% 
    filter(Rk <= 44) -> dat_avg
  
  ## シーズン情報
  dat_avg %>% 
    mutate(year = substr(X_Season, start = 1, stop = 4)) %>% 
    mutate(X_Season = as.integer(year)) %>%
    select(-year) -> dat_avg
  
  ## 身長を変換する
  dat_avg %>% 
    mutate(X_Ht = map_dbl(X_Ht, feet_to_meter)) %>% 
    mutate(X_Ht = round(X_Ht, 2)) -> dat_avg
  
  ## 2P%を算出する
  dat_avg %>% 
    mutate(`X_2P%` = (`X_eFG%` * X_FGA  - 1.5 *  X_3P ) / (X_FGA - X_3PA)) %>%
    mutate(`X_2PA` = (X_FGA - X_3PA)) %>% 
    mutate(`X_2P`  = `X_2P%` * `X_2PA`) -> dat_avg
  
  ## 3P%-eFGを算出する
  dat_avg %>% 
    mutate(`X_3P_eFG%`  = `X_3P%` * 1.5 ) -> dat_avg
  
  ### Rk(行番号)とX_Lg(リーグ)は除く
  dat_avg %>% 
    select(-Rk, -X_Lg) %>%
    pivot_longer(cols = !X_Season) -> dat_avg_long
    
  return(dat_avg_long)
}

dat_avg_per100 = read_csv("https://gist.githubusercontent.com/gghatano/5a250d08983d38ae34131e8d85524f7f/raw/42c305fb14ea967e556fc98f93f427a2099db3c9/NBA_LEAGUE_AVERAGE_PER_100_POSESSIONS.csv")
dat_avg_per100_long = preprocess_nba_league_avg_data(dat_avg_per100)

dat_avg_pergame = read_csv("https://gist.githubusercontent.com/gghatano/5a250d08983d38ae34131e8d85524f7f/raw/42c305fb14ea967e556fc98f93f427a2099db3c9/NBA_LEAGUE_AVERAGE_PER_GAME.csv")
dat_avg_pergame_long = preprocess_nba_league_avg_data(dat_avg_pergame)

unique_data_name = c("Per-100-Possession", "Per-Game")



```



NBA-League-Average(Per 100 Possesion) {data-icon="fa-globe"}
===============================================

Row {data-width=150}
-----------------------------------------------------------------------

### PER 100 Possessions (Left)
```{r}
unique_name = dat_avg_per100_long$name %>% unique

selectInput("name_per100_left", label = h4("Please select colname for visualize"), choices = unique_name)

renderPlotly({
  ggplotly(
    ggplot(dat_avg_per100_long %>% filter(name == input$name_per100_left), aes(x = X_Season, y = value)) +
    geom_line() + geom_point(color = "blue") + 
    theme(plot.margin = margin(2,.8, 2, .8, "cm")) + 
    labs(title= "NBA League Average(Per 100 Possessions)")
  )
})
```

### PER 100 Possesion (right)
```{r}

unique_name = dat_avg_pergame_long$name %>% unique

selectInput("name_per100_right", 
            label = h4("Please select colname for visualize"), choices = unique_name)

renderPlotly({
  ggplotly(
    ggplot(dat_avg_per100_long %>% filter(name == input$name_per100_right), aes(x = X_Season, y = value)) +
    geom_line() + geom_point(color = "blue") + 
    theme(plot.margin = margin(2,.8, 2, .8, "cm")) + 
    labs(title= "NBA League Average(Per 100 Possesions)")
  )
})

```

NBA-League-Average(Per Game) {data-icon="fa-globe"}
===============================================

Row {data-width=150}
-----------------------------------------------------------------------

### PER Game (Left)
```{r}
unique_name = dat_avg_pergame_long$name %>% unique

selectInput("name_pergame_left", label = h4("Please select colname for visualize"), choices = unique_name)

renderPlotly({
  ggplotly(
    ggplot(dat_avg_pergame_long %>% filter(name == input$name_pergame_left), aes(x = X_Season, y = value)) +
    geom_line() + geom_point(color = "blue") + 
    theme(plot.margin = margin(2,.8, 2, .8, "cm")) + 
    labs(title= "NBA League Average(Per Game)")
  )
})
```

### PER Game (right)
```{r}

unique_name = dat_avg_pergame_long$name %>% unique

selectInput("name_pergame_right", 
            label = h4("Please select colname for visualize"), choices = unique_name)

renderPlotly({
  ggplotly(
    ggplot(dat_avg_pergame_long %>% filter(name == input$name_pergame_right), aes(x = X_Season, y = value)) +
    geom_line() + geom_point(color = "blue") + 
    theme(plot.margin = margin(2,.8, 2, .8, "cm")) + 
    labs(title= "NBA League Average(Per Game)")
  )
})

```

Introduction {data-icon="fa-globe"}
===============================================

- [Basketball-reference](https://www.basketball-reference.com/leagues/NBA_stats_totals.html)のデータを、
[FlexDashboardの紹介ブログ記事](https://medium.com/@kar.prattusha/flex-dashboard-with-shiny-components-in-r-1229f3a3fa8a)を参考に、可視化してみます。

- TODO
  - 2つのグラフを同時に見せるようにパネルを分ける
    - [完了] per100に絞って、2つのグラフを表示した
    - [調査] データを選択するboxを置くと、グラフが小さくなる/はみ出すので諦めた(要調査)
  - ページ上部に気の利いた数字を出す
    - 検討中

